# build environment
FROM node:12 as build
WORKDIR /app
COPY package*.json ./
RUN yarn
COPY . .
RUN yarn build

# production environment
FROM nginx:stable
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]